include("${PROJECT_SOURCE_DIR}/VERSION.cmake")
set(ATUM_DRIVE_PROFILE "" CACHE STRING "Explicit immutable Atum profile: production or s2")
set_property(CACHE ATUM_DRIVE_PROFILE PROPERTY STRINGS production s2)
if(ATUM_DRIVE_PROFILE STREQUAL "production")
    set(ATUM_DRIVE_ORIGIN "https://drive.atumplatform.com")
    set(ATUM_MAS_ISSUER "https://auth.atumplatform.com/")
    set(APPLICATION_SHORTNAME "AtumDrive")
    set(APPLICATION_NAME "Atum Drive")
    set(APPLICATION_EXECUTABLE "atum-drive")
    set(APPLICATION_REV_DOMAIN "com.atumplatform.drive")
elseif(ATUM_DRIVE_PROFILE STREQUAL "s2")
    set(ATUM_DRIVE_ORIGIN "https://spike-drive.atumplatform.com")
    set(ATUM_MAS_ISSUER "https://spike-auth.atumplatform.com/")
    set(APPLICATION_SHORTNAME "AtumDriveTest")
    set(APPLICATION_NAME "Atum Drive Test")
    set(APPLICATION_EXECUTABLE "atum-drive-test")
    set(APPLICATION_REV_DOMAIN "com.atumplatform.drive.test")
else()
    message(FATAL_ERROR "Atum OEM requires explicit ATUM_DRIVE_PROFILE=production or s2")
endif()
set(ATUM_OAUTH_CLIENT_ID "01JDRVCMPNXQ7R8S9T0V2W3X4Y")
set(APPLICATION_VENDOR "Atum Platform")
set(APPLICATION_ICON_NAME "atum")
set(THEME_CLASS "AtumTheme")
set(THEME_INCLUDE "${CMAKE_CURRENT_LIST_DIR}/atumtheme.h")
set(VIRTUAL_FILE_SYSTEM_PLUGINS "off" CACHE STRING "Atum uses complete local files" FORCE)
set(WITH_CRASHREPORTER OFF CACHE BOOL "Atum identity build has no crash upload" FORCE)
set(WITH_AUTO_UPDATER OFF CACHE BOOL "Atum uses explicit update handoff" FORCE)
set(WITH_UPDATE_NOTIFICATION OFF CACHE BOOL "Atum uses explicit update handoff" FORCE)
if(APPLE)
    set(CMAKE_OSX_DEPLOYMENT_TARGET "14.0" CACHE STRING "Atum Mac minimum" FORCE)
endif()
configure_file("${CMAKE_CURRENT_LIST_DIR}/atumprofile.h.in" "${PROJECT_BINARY_DIR}/src/libsync/atumprofile.h" @ONLY)
